default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: app_service-rw
  password: jksadjf837q9a0JKJ3

development:
  <<: *default
  database: app_service_development

test:
  <<: *default
  database: app_service_test
