# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92308bf76b29af7ffdfc5b973460b13d21316a0197841b32a33b02b2e33472a5b829aa8bd00ad33a8f749915b1fc986c8396b445e8acc9d07a12e97d062e261c

test:
  secret_key_base: 3a03bf8b6287851e80183f32fa36c6182d44b9ebff14f7e7a8b610ee85e44bb65682dc95fa5a708cb54f3326b036255986a81db6a8ebc64382390e73bb7478dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
